#include <stdio.h>
#include <stdlib.h>
#include "../src/logger.h"

int main()
{
    int msg_count = 0;
    log_init("../out/exceed_buffer.log");
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    sleep(1);
    log_print(INFO, "Slept for 1 sec after logging 800 lines\n");
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    sleep(1);
    log_print(INFO, "Slept for 1 sec after logging 900 lines\n");
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_print(INFO, "Test INFO message %d\n", ++msg_count);
    log_print_debug("Test DEBUG message %d\n", ++msg_count);
    log_exit();
    return 0;
}
